# Generated by Django 5.1.5 on 2025-02-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question_bn',
            new_name='translated_question',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='question_lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
