# Generated by Django 5.1.5 on 2025-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_rename_question_bn_faq_translated_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='translated_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
