# Generated by Django 5.1.5 on 2025-02-01 18:29

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_faq_answer_lang_faq_translated_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer_lang',
            new_name='detected_lang',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='translated_answer',
            new_name='question_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_lang',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='translated_question',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
